// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (unpooled) connection; the app's runtime
    // PrismaClient uses the pooled DATABASE_URL via a driver adapter instead.
    // Locally and in CI this is DIRECT_URL; on Vercel the Neon integration
    // injects the unpooled string as DATABASE_URL_UNPOOLED, so fall back to it.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL_UNPOOLED"],
  },
});
